# ci.yml
name: Linter

on: [pull_request]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run lint
        run: |
          npm run lint
      - name: Run prettier
        run: |
          npm run format
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run test
        run: |
          nom run test
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    needs: [lint-format, unit-test]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run build
        run: |
          npm run build