# end to end test.yml
name: End to end

on: [pull_request]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # As its name stands for, this jobs will install the npm dependencies and cache them
  # unless they have been cached in a previous workflow run and remained unchanged.
  install-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache npm dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/npm.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install Dependencies
        # Check for `cache-hit` (`steps.cache-dependencies.cache-hit != 'true'`)
        # If there's a cache hit, we skip this step (the dependencies are already available)
        # If there's no cache hit, we run "npm install"
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          npm install --force --non-interactive
  # This job requires some dependencies to be installed to run. Thus we'll restore
  # the dependencies that have been previously cached and use them here.
 
  build:
    
    steps:
      - name: Run build
        run: |
          yarn build
      # This step in the build job will upload the build output generated by the previous step
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          # Give a unique name to your artifacts so they can be easily retrieved
          name: build-output
          # This example is based of a Next.JS build output, thus the .next path.
          # The path might need to be changed based on your build settings or the framework your team is using.
          path: .next
  e2e-tests-chrome:
    needs: build
    steps:
      # Here we restore the build output generated in the previous job by downloading the artifact we uploaded
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
          # Specify the path in which you wish to place your artiface.
          # Here I restore them in the .next folder since it's necessary to run the next start command later on
          path: .next
      - name: Run cypress
        uses: cypress-io/github-action@v2.10.1
        with:
          start: next start
          browser: chrome
  e2e-tests-firefox:
    needs: build
    steps:
      # Here we restore the same build output as we did in the e2e-tests-chrome job
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: .next
      - name: Run cypress
        uses: cypress-io/github-action@v2.10.1
        with:
          start: next start
          browser: firefox