name: End to end

on: [pull_request]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  install-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache npm dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/npm.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          npm install --force --non-interactive

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Run build
        run: |
          npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: ../../.next

  e2e-tests-chrome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: ../../.next
      - name: Run cypress
        uses: cypress-io/github-action@v2.10.1
        with:
          start: next start
          browser: chrome

  e2e-tests-firefox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: ../../.next
      - name: Run cypress
        uses: cypress-io/github-action@v2.10.1
        with:
          start: next start
          browser: firefox